---
title: "Raster Builder"
author: "Lucas Boyd"
date: "11/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(raster)
library(tmap)
library(sf)
library(raster)
library(terra)

```

```{r}
# ABANDONMENT 
ssp1 <- rast(here("data", "chen", "SSP1_abandoned_cropland_2050_global.tif"))
ssp2 <- rast(here("data", "chen", "SSP2_abandoned_cropland_2050_global.tif"))
ssp3 <- rast(here("data", "chen", "SSP3_abandoned_cropland_2050_global.tif"))
ssp4 <- rast(here("data", "chen", "SSP4_abandoned_cropland_2050_global.tif")) 
ssp5 <- rast(here("data", "chen", "SSP5_abandoned_cropland_2050_global.tif")) 

# CARBON
carbon <- rast(here("data", "carbon", "sequestration_rate__mean__aboveground__full_extent__Mg_C_ha_yr.tif"))

# Biodiversity
bd <- rast(here("data", "bd", "sparc_conservationPriorities.tif"))

# quick plots to show outputs
plot(carbon)
plot(ssp1)
plot(bd)
```
# quickly change the resolution of any of the rasters
```{r}
# determine factor by which to expand abandonment raster
abandon_factor <- 50 # for SSP abandonment rasters (original = 1k)
carbon_factor <- 50 # for carbon layer (original = 1k)
bd_factor <- 2 # for biodiversity layer (original = ~5k)

## Is this easier than just putting the numbers in the aggregate() fxn? -NM
```

# create abandonment rasters
# SSP1
```{r}
# aggregate SSP1 to 50k resolution
ssp1_aggregate <- aggregate(ssp1, fact = abandon_factor, fun = sum) %>% project("epsg:4326")

# replacing zeros with NA values for visualization
ssp1_aggregate[ssp1_aggregate == 0] <- NA

# changing to proportion abandonment
ssp1_aggregate <- ssp1_aggregate/(abandon_factor*abandon_factor)

# save out the raster

## changed filename to automatically save in correct folder
## that way you don't manually have to move it and reload within this code chunk -NM
writeRaster(ssp1_aggregate, filename = "data/50k/ssp1_50k.tif", overwrite = TRUE)

ssp1_50k <- rast(here("data", "50k", "ssp1_50k.tif")) 

plot(ssp1_50k)
```


```{r}
tmap_mode(mode = "view")
tm_shape(ssp1_50k) + 
  tm_raster()
```

# SSP2
```{r}
# aggregate to 50k resolution
ssp2_aggregate <- aggregate(ssp2, fact = abandon_factor, fun = sum) 

# replacing zeros with NA values for visualization
ssp2_aggregate[ssp2_aggregate == 0] <- NA

# changing to a proportion abandonment
ssp2_aggregate <- ssp2_aggregate/(abandon_factor*abandon_factor)


# save out the raster
writeRaster(ssp2_aggregate, filename = "data/50k/ssp2_50k.tif", overwrite = TRUE)

ssp2_50k <- rast(here("data", "50k", "ssp2_50k.tif"))

```

# SSP3
```{r}
# aggregate to 50k resolution
ssp3_aggregate <- aggregate(ssp3, fact = abandon_factor, fun = sum)

# replacing zeros with NA values for visualization
ssp3_aggregate[ssp3_aggregate == 0] <- NA

# changing to a proportion abandonment
ssp3_aggregate <- ssp3_aggregate/(abandon_factor*abandon_factor)

# save out the raster
writeRaster(ssp3_aggregate, filename = "data/50k/ssp3_50k.tif", overwrite = TRUE)

ssp3_50k <- rast(here("data", "50k", "ssp3_50k.tif"))

```

# SSP4
```{r}
# aggregate to 50k resolution
ssp4_aggregate <- aggregate(ssp4, fact = abandon_factor, fun = sum)

# replacing zeros with NA values for visualization
ssp4_aggregate[ssp4_aggregate == 0] <- NA

# changing to a proportion abandonment
ssp4_aggregate <- ssp4_aggregate/(abandon_factor*abandon_factor)

# save out the raster
writeRaster(ssp4_aggregate, filename = "data/50k/ssp4_50k.tif", overwrite = TRUE)

ssp4_50k <- rast(here("data", "50k", "ssp4_50k.tif"))

```

# SSP5

```{r}
# aggregate to 50k resolution
ssp5_aggregate <- aggregate(ssp5, fact = abandon_factor, fun = sum)

# replacing zeros with NA values for visualization
ssp5_aggregate[ssp5_aggregate == 0] <- NA

# changing to a proportion abandonment
ssp5_aggregate <- ssp5_aggregate/(abandon_factor*abandon_factor)

# save out the raster
writeRaster(ssp5_aggregate, filename = "data/50k/ssp5_50k.tif", overwrite = TRUE)

ssp5_50k <- rast(here("data", "50k", "ssp5_50k.tif"))
```

# CARBON

```{r}
# change carbon to CRS of abandonment then project in same crs
carbon_aggregate <- carbon %>% 
  aggregate(fact = carbon_factor, fun = mean, na.rm = TRUE) %>% 
  project(y = crs(ssp1_50k))

# make carbon layer exactly match the spatial extent of the abandonment
# carbon_resamp <- resample(carbon_aggregate, ssp1_50k, method = "bilinear")

# saving out the raster
writeRaster(carbon_aggregate, filename = "data/carbon/carbon_50k.tif", overwrite = TRUE)

carbon_50k <- rast(here("data", "carbon", "carbon_50k.tif"))

plot(carbon_50k)
```

# BIODIVERSITY - projection still coming up weird
```{r, eval= FALSE}
# change biodiversity to CRS of abandonment then project in same crs
bd_aggregate <- bd %>% 
  aggregate(fact = bd_factor, fun = mean, na.rm = TRUE) %>% 
  project(y = crs(ssp1_50k))

# make carbon layer exactly match the spatial extent of the abandonment
bd_resamp <- resample(bd_aggregate, ssp1_50k, method = "bilinear")

plot(bd_resamp)
plot(carbon_50k, add = TRUE)


# saving out the raster
# writeRaster(bd_aggregate, filename = "bd_50k.tif", overwrite = TRUE)
tmap_mode(mode = "view")
tm_shape(bd_aggregate) + 
  tm_raster("sparc_conservationPriorities")
bd_aggregate
```

