---
title: "shiny_obj1_explore"
author: "Lucas Boyd"
date: "10/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(raster)
library(tmap)
library(sf)
library(raster)
library(terra)
```

```{r}
ssp1 <- raster(here("data", "chen", "SSP1_abandoned_cropland_global.tif"))
ssp2 <- raster(here("data", "chen", "SSP2_abandoned_cropland_global.tif"))
ssp3 <- raster(here("data", "chen", "SSP3_abandoned_cropland_global.tif"))
ssp4 <- raster(here("data", "chen", "SSP4_abandoned_cropland_global.tif"))
ssp5 <- raster(here("data", "chen", "SSP5_abandoned_cropland_global.tif"))

carbon <- raster(here("data", "carbon", "sequestration_rate__mean__aboveground__full_extent__Mg_C_ha_yr.tif"))


bd <- raster(here("data", "bd", "sparc_conservationPriorities.tif"))

plot(carbon)
plot(ssp1)
plot(bd)



```

# aggregating the layers
```{r}
# ssp1
ssp1_aggregate <- aggregate(ssp1, fact = 50, expand = FALSE, fun = sum)
plot(ssp1_aggregate)
writeRaster(ssp1_aggregate, filename = "ssp1_50k.tif")

ssp1_50k <- raster(here("ssp1_50k.tif"))
```


```{r}
# carbon
carbon_aggregate <- aggregate(carbon, fact = 50, expand = FALSE, fun = mean)
plot(carbon_aggregate)
writeRaster(carbon_aggregate, filename = "carbon_50k.tif", overwrite = TRUE)
```


```{r}
# bd
bd <- projectRaster(bd, crs = crs(ssp1))  
bd_aggregate <- aggregate(bd, fact = 10, expand = FALSE, fun = mean)
plot(bd_aggregate)
writeRaster(bd_aggregate, filename = "bd_50k.tif", overwrite = TRUE)
```


```{r}
bd
carbon
ssp1
```

# WORKING MAP AS OF NOW, need to....
- figure out how to divide values by 2500
- turn the zeros into NAs 
- organize it by country

~~~ at this point I can build out the structure of the Shiny

- get the carbon and bd layers to same resolution
- merge the rasters into 1 super raster with all 3 layers
- 
```{r}
tmap_mode(mode = "view")
      tm_raster(col = "ssp1_50k", palette = "Reds", style = "cont", alpha = 0.5)
      
  

```


# t map explore
```{r}

```
## START HERE
```{r}
# read in the aggregated layers
ssp1_50k <- raster(here("data", "50k", "ssp1_50k.tif"))
carbon_50k <- raster(here("data", "50k", "carbon_50k.tif"))
bd_50k <- raster(here("data", "0k", "bd_50k.tif"))
plot(bd_50k)
plot(carbon_50k)
plot(ssp1_50k)
bd_50k

carbon_50k

ssp1_50k
```

```{r}
# replacing zeros with NAs in the 
ssp1_50k[ssp1_50k == 0] <- NA
```

```{r}
tmap_mode(mode = "view")

tm_shape(ssp1_50k) + 
  tm_raster(col = "ssp1_50k", palette = "Reds", style = "cont", alpha = .7)

tm_shape(carbon_50k) + 
  tm_raster(col = "carbon_50k", palette = "Blues", style = "cont", alpha = .7)
```


```{r}
tm_shape(bd_50k) + 
  tm_raster(col = "bd_50k", palette = "Greens", style = "cont", alpha = 0.5)
      
```



